UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 1;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 2;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 3;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 4;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 5;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 6;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 7;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 8;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 9;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 10;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 11;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 12;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 13;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 14;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 15;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 16;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 17;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 18;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 19;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 20;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 21;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 22;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 23;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 24;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 25;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 26;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 27;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 28;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 29;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 30;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 31;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 32;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 33;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 34;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 35;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 36;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 37;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 38;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 39;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 40;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 41;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 42;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 43;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 44;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 45;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 46;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 47;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 48;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 49;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 50;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 51;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 52;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 53;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 54;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 55;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 56;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 57;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 58;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 59;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 60;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 61;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 62;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 63;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 64;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 65;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 66;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 67;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 68;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 69;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 70;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 71;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 72;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 73;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 74;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 75;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 76;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 77;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 78;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 79;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 80;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 81;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 82;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 83;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 84;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 85;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 86;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 87;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 88;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 89;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 90;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 91;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 92;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 93;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 94;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 95;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 96;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 97;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 98;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 99;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 100;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 101;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 102;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 103;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 104;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 105;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 106;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 107;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 108;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 109;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 110;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 111;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 112;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 113;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 114;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 115;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 116;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 117;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 118;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 119;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 120;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 121;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 122;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 123;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 124;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 125;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 126;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 127;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 128;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 129;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 130;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 131;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 132;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 133;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 134;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 135;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 136;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 137;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 138;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 139;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 140;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 141;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 142;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 143;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 144;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 145;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 146;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 147;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 148;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 149;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 150;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 151;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 152;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 153;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 154;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 155;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 156;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 157;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 158;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 159;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 160;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 161;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 162;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 163;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 164;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 165;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 166;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 167;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 168;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 169;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 170;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 171;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 172;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 173;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 174;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 175;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 176;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 177;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 178;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 179;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 180;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 181;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 182;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 183;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 184;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 185;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 186;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 187;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 188;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 189;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 190;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 191;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 192;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 193;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 194;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 195;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 196;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 197;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 198;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 199;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 200;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 201;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 202;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 203;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 204;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 205;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 206;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 207;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 208;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 209;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 210;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 211;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 212;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 213;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 214;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 215;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 216;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 217;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 218;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 219;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 220;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 221;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 222;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 223;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 224;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 225;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 226;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 227;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 228;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 229;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 230;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 231;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 232;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 233;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 234;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 235;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 236;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 237;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 238;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 239;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 240;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 241;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 242;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 243;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 244;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 245;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 246;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 247;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 248;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 249;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 250;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 251;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 252;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 253;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 254;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 255;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 256;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 257;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 258;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 259;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 260;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 261;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 262;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 263;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 264;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 265;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 266;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 267;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 268;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 269;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 270;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 271;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 272;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 273;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 274;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 275;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 276;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 277;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 278;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 279;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 280;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 281;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 282;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 283;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 284;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 285;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 286;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 287;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 288;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 289;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 290;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 291;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 292;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 293;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 294;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 295;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 296;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 297;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 298;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 299;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 300;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 301;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 302;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 303;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 304;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 305;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 306;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 307;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 308;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 309;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 310;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 311;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 312;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 313;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 314;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 315;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 316;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 317;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 318;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 319;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 320;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 321;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 322;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 323;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 324;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 325;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 326;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 327;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 328;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 329;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 330;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 331;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 332;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 333;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 334;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 335;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 336;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 337;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 338;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 339;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 340;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 341;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 342;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 343;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 344;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 345;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 346;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 347;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 348;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 349;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 350;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 351;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 352;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 353;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 354;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 355;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 356;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 357;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 358;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 359;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 360;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 361;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 362;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 363;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 364;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 365;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 366;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 367;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 368;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 369;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 370;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 371;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 372;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 373;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 374;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 375;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 376;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 377;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 378;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 379;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 380;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 381;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 382;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 383;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 384;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 385;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 386;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 387;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 388;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 389;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 390;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 391;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 392;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 393;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 394;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 395;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 396;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 397;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 398;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 399;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 400;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 401;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 402;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 403;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 404;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 405;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 406;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 407;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 408;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 409;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 410;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 411;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 412;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 413;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 414;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 415;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 416;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 417;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 418;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 419;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 420;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 421;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 422;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 423;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 424;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 425;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 426;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 427;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 428;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 429;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 430;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 431;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 432;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 433;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 434;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 435;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 436;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 437;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 438;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 439;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 440;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 441;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 442;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 443;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 444;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 445;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 446;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 447;
UPDATE hospede SET nacionalidade = 'Arábia Saudita' WHERE cod_hosp = 448;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 449;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 450;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 451;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 452;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 453;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 454;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 455;
UPDATE hospede SET nacionalidade = 'Japão' WHERE cod_hosp = 456;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 457;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 458;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 459;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 460;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 461;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 462;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 463;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 464;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 465;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 466;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 467;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 468;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 469;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 470;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 471;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 472;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 473;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 474;
UPDATE hospede SET nacionalidade = 'Argentina' WHERE cod_hosp = 475;
UPDATE hospede SET nacionalidade = 'China' WHERE cod_hosp = 476;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 477;
UPDATE hospede SET nacionalidade = 'México' WHERE cod_hosp = 478;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 479;
UPDATE hospede SET nacionalidade = 'Austrália' WHERE cod_hosp = 480;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 481;
UPDATE hospede SET nacionalidade = 'Coreia do Sul' WHERE cod_hosp = 482;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 483;
UPDATE hospede SET nacionalidade = 'África do Sul' WHERE cod_hosp = 484;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 485;
UPDATE hospede SET nacionalidade = 'Estados Unidos' WHERE cod_hosp = 486;
UPDATE hospede SET nacionalidade = 'Brasil' WHERE cod_hosp = 487;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 488;
UPDATE hospede SET nacionalidade = 'França' WHERE cod_hosp = 489;
UPDATE hospede SET nacionalidade = 'Turquia' WHERE cod_hosp = 490;
UPDATE hospede SET nacionalidade = 'Rússia' WHERE cod_hosp = 491;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 492;
UPDATE hospede SET nacionalidade = 'Alemanha' WHERE cod_hosp = 493;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 494;
UPDATE hospede SET nacionalidade = 'Índia' WHERE cod_hosp = 495;
UPDATE hospede SET nacionalidade = 'Itália' WHERE cod_hosp = 496;
UPDATE hospede SET nacionalidade = 'Reino Unido' WHERE cod_hosp = 497;
UPDATE hospede SET nacionalidade = 'Canadá' WHERE cod_hosp = 498;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 499;
UPDATE hospede SET nacionalidade = 'Indonésia' WHERE cod_hosp = 500;
